### ISSUE TITLE
The algorithm has a bug

### ISSUE THREAD

**Issue by gaow0007** [hoohack/TicTacToe#1]
Player first;
First choose (1, 2);
Second choose (3, 3)
Third choose (1, 3)
Now player wins, however the page shows computer wins

**Comment by hoohack** [comment]
I play as you described.However the result is computer win,would you mind
play again or show me a screenshot?thank you.

thanks
Hector

2016-05-02 16:41 GMT+08:00 SaberArthurus notifications@github.com:

**Comment by gaow0007** [comment]
The page shows computer win, however the player has won.
![image](https://cloud.githubusercontent.com/assets/16629752/14976426/31a05aec-113e-11e6-80f5-befdc0203a28.png)
You can choose x and player first.

**Comment by hoohack** [comment]
I see.The bug has fixed.Thank you for your report.
